# Generated by Django 6.0.3 on 2026-03-12 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('news', '0009_edition_article_edition_category_edition'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='edition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.edition'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('reporter', 'Reporter'), ('subeditor', 'SubEditor'), ('editor', 'Editor'), ('paginator', 'Paginator')], max_length=20),
        ),
    ]
