# Generated by Django 6.0.3 on 2026-03-10 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_articleversion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('subeditor_review', 'SubEditor Review'), ('editor_sent_back', 'Sent Back by Editor'), ('editor_approved', 'Editor Approved'), ('pagination', 'Pagination'), ('published', 'Published')], default='draft', max_length=30),
        ),
    ]
