# Generated by Django 6.0.3 on 2026-03-10 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_article_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='editor_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
