# Generated by Django 6.0.3 on 2026-03-11 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_pagelayout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagelayout',
            name='position',
        ),
        migrations.AddField(
            model_name='pagelayout',
            name='slot_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
