# Generated by Django 6.0.3 on 2026-03-12 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_edition_article_edition_category_edition'),
    ]

    operations = [
        migrations.AddField(
            model_name='edition',
            name='total_pages',
            field=models.IntegerField(default=16),
        ),
    ]
